### PR TITLE
Give the cat some actions 

### PR DESCRIPTION
**Pull request by wp-michael**
This pulls the response determination into a class.
It adds the concept of actions with some simple replacement so some actions happen against an item or in a place.

### CODE REVIEW

**Comment by UnrealApex** [comment]
Is this PR supposed to implement #2?

**Comment by wp-michael** [comment]
It looks like it does!
Seems knocking things off of places is a requirement for a cat-like behavior.

**Comment by UnrealApex** [comment]
It would be cute, but I think it makes CatGPT resemble ChatGPT a little bit less.

**Comment by woutervdijke** [comment]
The class interpretation is neat, but I think adding actions in the responses by default would detract from the joke a bit. As The Verge put it: _no thinking, no words, just meow meow meow_.

Maybe an action in response to a specific input prompt would be fun as an easter egg... open to suggestions for that.

**Comment by UnrealApex** [comment]
I agree. Perhaps we could add more easter eggs to silly prompts users might give.

**Pull request closed without merging**
